module.exports = {
  content: [
    "./pages/_app.tsx",
    "./pages/index.tsx",
    "./pages/components/Header.tsx",
    "./pages/components/Hero.tsx",
    "./pages/components/Input.tsx",
    "./pages/components/Carousel.tsx",
    "./pages/components/EarlyAccess.tsx",
    "./pages/components/Choose.tsx",
    "./pages/components/HowToBuy.tsx",
    "./pages/components/APR.tsx",
    "./pages/components/Featured.tsx",
    "./pages/components/Clear.tsx",
    "./pages/components/Trending.tsx",
    "./pages/components/Pay.tsx",
    "./pages/components/Footer.tsx",
    "./pages/components/ShopCollapsed.tsx",
    "./pages/components/WaysToPayCollapsed.tsx",
    "./pages/components/ForBusinessCollapsed.tsx",
    "./pages/components/EarnCollapsed.tsx",
    "./pages/components/SignInCollapsed.tsx",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
